---
system_toolbox_dedicated_user_enabled: false
system_toolbox_user: system-toolbox
system_toolbox_home: "/var/lib/{{ system_toolbox_user }}"
system_toolbox_local_source: ""
system_toolbox_dir: "/home/{{ deploy_user }}/work/python/system-toolbox"
system_toolbox_traverse_paths:
  - "/home/{{ deploy_user }}"
  - "/home/{{ deploy_user }}/work"
  - "/home/{{ deploy_user }}/work/python"
system_toolbox_host: "0.0.0.0"
system_toolbox_port: 8789
system_toolbox_uv_path: "/home/{{ deploy_user }}/.local/bin/uv"
system_toolbox_source_url: ""
system_toolbox_privileged_units: []
system_toolbox_privileged_user_units: {}
deploy_user_uid: 1000
